# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 24.x ]  # Oldest 'Active' version: https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run test:mutant

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports_node${{ matrix.node-version }}
          path: |
            reports/
            coverage/
      - name: Upload dist/ directory
        uses: actions/upload-artifact@v4
        with:
          name: dist_node${{ matrix.node-version }}
          path: dist/
